### ISSUE TITLE
[Proposal] some extra param to avoid string formatting

### ISSUE THREAD

**Issue by digitronik** [omaciel/fauxfactory#102]
While using some string category method user like to matriculate string; they want string `start` with something. Its most common use-case; which, I observed while using `fauxfactory` in daily life. It will reduce lots of indirect string formatting.
```
def gen_alphanumeric(length=10, start=None):
    pass
```

small example:
```
In [1]: from fauxfactory import gen_alpha, gen_alphanumeric                                                                                       

In [2]: gen_alpha(start="volume")                                                                                                                 
Out[2]: 'volume_DGDvJNxZmO'

In [3]: gen_alpha(3, start="og")                                                                                                                  
Out[3]: 'og_OpD'

In [4]: gen_alphanumeric(start="vol")                                                                                                             
Out[4]: 'vol_DJBGf7Af2L'

In [5]: gen_alphanumeric(5, start="vol")                                                                                                          
Out[5]: 'vol_3pmw0'
```

This is basic example. we can go for more enhancement, we can even take care of `string length`.

**Comment by Yadnyawalkya** [comment]
Great proposal! 

I have some similar idea for this feature, you might have seen this thing from `tempfile` module. So, in `tempfile`, if you wanted to make file whose name starts with or ends with something, we do it with `suffix=` and `prefix=` args.

```
In [1]: import tempfile

In [2]: tempfile.NamedTemporaryFile(suffix='.pdf').name
Out[2]: '/tmp/tmpE89Tdd.pdf'

In [3]: tempfile.NamedTemporaryFile(prefix='test_').name
Out[3]: '/tmp/test_2RMf6N'
```

It is very similar to nikhil's idea and it would be great if we include them with it.
Thoughts @digitronik  @omaciel ?

**Comment by omaciel** [comment]
@Yadnyawalkya yup, agreed with the approach :) Anyone wants to send me a PR?

**Comment by digitronik** [comment]
@omaciel PR is ready... I tried and after that only I added proposal. But I like to cover `unit test` :). I will raise soon. 

Thanks.
