### ISSUE TITLE
Add start argument to gen_uuid

### ISSUE THREAD

**Issue by valaparthvi** [omaciel/fauxfactory#113]
I see a wide use case of `gen_uuid` in Insights plugin such as drift if we can enhance it to take `start` argument. We're currently  using the manual way of formatting string and `uuid` to generate our desired uuid, but I would like to start using fauxfactory within the plugin and this feature would help kickstart the usage.

I would like to take this up if the feature seems good enough.

**Comment by omaciel** [comment]
Sure thing. Please send me your PR.

**Comment by valaparthvi** [comment]
It might not be such a good idea after all, because passing a `start` argument will not give a valid uuid4 string and I do not think that is a good idea. Hence closing this issue and PR #114 .
