### ISSUE TITLE
Move formatting to Black?

### ISSUE THREAD

**Issue by JacobCallahan** [omaciel/fauxfactory#125]
We've done this in some other projects, but the main idea is to let black handle all code formatting so contributors don't have to.
We can then add a black run to the checks to ensure that submitted code is styled correctly.
There are a couple of things to decide with black, namely:

- String formatting. Keep single quotes or let black do doubles?
- Line length. Keep it capped at 80 or push it to around 100?

**Comment by JacobCallahan** [comment]
@omaciel @elyezer I'm curious what your thoughts are on this. If it is something you'd like to see, I can make the changes.

**Comment by omaciel** [comment]
I am confident that whatever you decide for defaults will be fine :) Let me know if you'd like to become a maintainer, too, as I have barely looked at or touched this code in quite some time :)

**Comment by JacobCallahan** [comment]
@omaciel then I'll just go wild with power! Let's see what @elyezer thinks since he's also contributed recently :)

**Comment by elyezer** [comment]
I have not preference for the quotes style. For the line length I personally use around 80 but this is something I would not argue to much to keep it.

Since you are bringing this up feel free to pick whatever you think will make more sense.

**Comment by JacobCallahan** [comment]
Thanks! Robottelo's kept single quotes, but we've moved line length out to ~99-100 and it's been nice.

**Comment by elyezer** [comment]
@JacobCallahan sounds like a plan. Thank you
