### ISSUE TITLE
python-2.6 support

### ISSUE THREAD

**Issue by jlaska** [omaciel/fauxfactory#73]
Is there interest in extending fauxfactory to work with python-2.6?

The main blocker I'm aware of is the existing use of `sys.version_info.major`.  On python-2.6, you'd need to use `sys.version_info[0]`.  If there is interest, I can send over a pull request.

**Comment by omaciel** [comment]
No reason why we wouldn't support it specially if it comes with a PR :)

**Comment by jlaska** [comment]
While I'm at it, any objections to using `pytest` to run the existing unittests?  The reason being that the `unittest` dependencies are not `python-2.6` friendly.  I'm finding it far simpler to just migrate tests over to pytest.

**Comment by Ichimonji10** [comment]
@jlaska unittest is part of the standard library in Python 2.6. How could its dependencies be unfriendly to Python 2.6?

**Comment by jlaska** [comment]
I believe `discover` is 2.7+.  

```
Many new features were added to unittest in Python 2.7, including test
discovery. unittest2 allows you to use these features with earlier versions
of Python.
```
You'd need to migrate to [unittest2](https://pypi.python.org/pypi/unittest2).  I started down that path, but just had better luck using `pytest` as the runner+collector.

**Comment by jlaska** [comment]
I've submitted #74 for review.  We can close this card and track the PR if you prefer.

**Comment by hugovk** [comment]
https://github.com/omaciel/fauxfactory/pull/74 is merged, can this be closed?
