### ISSUE TITLE
fauxfactory creates random length html values instead of the supplied length

### ISSUE THREAD

**Issue by sthirugn** [omaciel/fauxfactory#80]
I expected an html string of length `10` from the below example but I got `27`.  This fails some of my boundary condition tests.

``` sh
>>> value = gen_html(10)
>>> print value
<iframe>WusEPPqPSP</iframe>
>>> len(value)
27
```

**Comment by omaciel** [comment]
@sthirugn the `gen_html` method generates a string of length `x` surrounded by html tags. I can update the docstring to make it clearer. Generating a html string that iss exactly `x` characters long would be hard and limited to the size of existing html tags (eg. `body`, `strong`, etc)

**Comment by sthirugn** [comment]
:+1: to docstring update with a clear note that the returned data length will be ` passed in length + x ` where x can be a random int.

**Comment by renzon** [comment]
@sthirugn : You can use gen_html_with_total_len: https://github.com/omaciel/fauxfactory/pull/82/files#diff-d8166b09dd05de32f08240db1a10ac69R819. I had the same same need and implemented it ;). @omaciel I would close this issue but I don't have permissions. Can you give me?

**Comment by sthirugn** [comment]
Thank you @renzon
