### ISSUE TITLE
whl on pypi does not include facts.json

### ISSUE THREAD

**Issue by m-bucher** [omaciel/fauxfactory#97]
The whl on pypi (https://pypi.python.org/packages/11/c9/e69a791e2406c110e861b6667984b5d7117d46d8db19ba6233b3f792f1a1/fauxfactory-3.0.0-py2.py3-none-any.whl#md5=542e03137577637198fe57db1396f099) does not include the fact.json file.

This results in a crash when trying to import fauxfactory:
`IOError: [Errno 2] No such file or directory: '/.../ansible-venv/lib/python2.7/site-packages/fauxfactory/facts.json'`

**Comment by omaciel** [comment]
The solution also required adding `include_package_data=True` as per https://python-packaging.readthedocs.io/en/latest/non-code-files.html

Fixed by 8f7d547
